env: dev
db:
  user: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
  name: ${POSTGRES_DB}
  host: ${POSTGRES_HOST}
  port: ${POSTGRES_PORT}
  sslmode: ${POSTGRES_SSLMODE}
server:
  host: "localhost"
  port: 8080
app:
  messageMaxLen: 100
  ttl: 50m
  sleepTime : 30s
  # supported log levels: debug info warn error
  loglvl: info